from pyquil import Program, get_qc
from pyquil.gates import H, CNOT, MEASURE
from functools import reduce
import numpy as np

shots = 1024

p = Program()

ro = p.declare('ro', memory_type='BIT', memory_size=8)

p.inst(H(0))
p.inst(CNOT(0, 3))
p.inst(CNOT(0, 6))
p.inst(H(0))
p.inst(H(3))
p.inst(H(6))
p.inst(CNOT(0, 1))
p.inst(CNOT(3, 4))
p.inst(CNOT(6, 7))
p.inst(CNOT(0, 2))
p.inst(CNOT(3, 5))
p.inst(CNOT(6, 8))
p.inst(CNOT(0, 9))
p.inst(CNOT(1, 9))
p.inst(CNOT(1, 10))
p.inst(CNOT(2, 10))
p.inst(CNOT(3, 11))
p.inst(CNOT(4, 11))
p.inst(CNOT(4, 12))
p.inst(CNOT(5, 12))
p.inst(CNOT(6, 13))
p.inst(CNOT(7, 13))
p.inst(CNOT(7, 14))
p.inst(CNOT(8, 14))
p.inst(MEASURE(9, ro[0]))
p.inst(MEASURE(10, ro[1]))
p.inst(MEASURE(11, ro[2]))
p.inst(MEASURE(12, ro[3]))
p.inst(MEASURE(13, ro[4]))
p.inst(MEASURE(14, ro[5]))
p.inst(H(0))
p.inst(H(1))
p.inst(H(2))
p.inst(H(3))
p.inst(H(4))
p.inst(H(5))
p.inst(H(6))
p.inst(H(7))
p.inst(H(8))
p.inst(CNOT(0, 15))
p.inst(CNOT(3, 16))
p.inst(CNOT(1, 15))
p.inst(CNOT(4, 16))
p.inst(CNOT(2, 15))
p.inst(CNOT(5, 16))
p.inst(CNOT(3, 15))
p.inst(CNOT(6, 16))
p.inst(CNOT(4, 15))
p.inst(CNOT(7, 16))
p.inst(CNOT(5, 15))
p.inst(CNOT(8, 16))
p.inst(MEASURE(15, ro[6]))
p.inst(MEASURE(16, ro[7]))
p.inst(H(0))
p.inst(H(1))
p.inst(H(2))
p.inst(H(3))
p.inst(H(4))
p.inst(H(5))
p.inst(H(6))
p.inst(H(7))

p.wrap_in_numshots_loop(shots)

qc = get_qc('17q-qvm')
results_list = qc.run(p)
results = list(map(lambda arr: reduce(lambda x, y: str(x) + str(y), arr[::-1], ""), results_list))
counts = dict(zip(results,[results.count(i) for i in results]))
print(counts)
