import cirq
import numpy as np
from functools import reduce

q = [cirq.NamedQubit('q' + str(i)) for i in range(12)]

circuit = cirq.Circuit(
    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    # Export to cirq WARNING: unknown gate "u".    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[4]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[4]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[4]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[4]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[5]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[5]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[5]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[5]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[6]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[6]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[6]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[6]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[7]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[7]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[7]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[7]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[4], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[4], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[10]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[5], q[10]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[10]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[10], q[11]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[6], q[11]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[10], q[11]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[11], q[8]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[7], q[8]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[11], q[8]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[7], q[8]),
    cirq.CNOT(q[7], q[11]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[7], q[11]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[10], q[11]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[6], q[11]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[10], q[11]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[10]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[5], q[10]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[10]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[4], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[4], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[4]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[4]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[4]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[4]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[5]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[5]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[5]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[5]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[6]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[6]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[6]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[6]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[7]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[7]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[9], q[7]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[7]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[9]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[2]),
    cirq.CNOT(q[0], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.measure(q[0], key='c00'),
    cirq.measure(q[1], key='c01'),
    cirq.measure(q[2], key='c02')
)

simulator = cirq.Simulator()
result = simulator.run(circuit, repetitions=1024)
result_dict = dict(result.multi_measurement_histogram(keys=['c00', 'c01', 'c02', ]))
keys = list(map(lambda arr: reduce(lambda x, y: str(x) + str(y), arr[::-1]), result_dict.keys()))
counts = dict(zip(keys,[value for value in result_dict.values()]))
print(counts)