from pyquil import Program, get_qc
from pyquil.gates import CNOT
from functools import reduce
import numpy as np

shots = 1024

p = Program()

# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
p.inst(CNOT(1, 0))
p.inst(CNOT(3, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
p.inst(CNOT(3, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 2))
p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 0))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 0))
# Export to pyquil WARNING: unknown gate "u".
p.wrap_in_numshots_loop(shots)

qc = get_qc('4q-qvm')
print(qc.run(p))
