import cirq
import numpy as np
from functools import reduce

q = [cirq.NamedQubit('q' + str(i)) for i in range(4)]

circuit = cirq.Circuit(
    # Export to cirq WARNING: unknown gate "u".    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    cirq.CNOT(q[1], q[0]),
    cirq.CNOT(q[3], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    cirq.CNOT(q[3], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[3]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[2]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[0], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[2]),
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[1]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[3], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[2], q[0]),
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    # Export to cirq WARNING: unknown gate "u".,
    cirq.CNOT(q[1], q[0]),
    # Export to cirq WARNING: unknown gate "u".
)

simulator = cirq.Simulator()
result = simulator.run(circuit, repetitions=1024)
result_dict = dict(result.multi_measurement_histogram(keys=[]))
keys = list(map(lambda arr: reduce(lambda x, y: str(x) + str(y), arr[::-1]), result_dict.keys()))
counts = dict(zip(keys,[value for value in result_dict.values()]))
print(counts)