from pyquil import Program, get_qc
from pyquil.gates import CNOT, MEASURE
from functools import reduce
import numpy as np

shots = 1024

p = Program()

ro = p.declare('ro', memory_type='BIT', memory_size=3)

# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 3))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 3))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 4))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 4))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 4))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 4))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 5))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 5))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 5))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 5))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 6))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 6))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 6))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 6))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 7))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 7))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 7))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 7))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(4, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(4, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 10))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(5, 10))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 10))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(10, 11))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(6, 11))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(10, 11))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(11, 8))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(7, 8))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(11, 8))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(7, 8))
p.inst(CNOT(7, 11))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(7, 11))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(10, 11))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(6, 11))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(10, 11))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 10))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(5, 10))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 10))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(4, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(3, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(4, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 3))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 3))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 3))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 4))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 4))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 4))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 4))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 5))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 5))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 5))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 5))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 6))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 6))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 6))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 6))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 7))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 7))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(9, 7))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 7))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(2, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 9))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 2))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 2))
# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(1, 2))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 2))
p.inst(CNOT(0, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(CNOT(0, 1))
# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".# Export to pyquil WARNING: unknown gate "u".p.inst(MEASURE(0, ro[0]))
p.inst(MEASURE(1, ro[1]))
p.inst(MEASURE(2, ro[2]))

p.wrap_in_numshots_loop(shots)

qc = get_qc('12q-qvm')
results_list = qc.run(p)
results = list(map(lambda arr: reduce(lambda x, y: str(x) + str(y), arr[::-1], ""), results_list))
counts = dict(zip(results,[results.count(i) for i in results]))
print(counts)
