import cirq
import numpy as np
from functools import reduce

q = [cirq.NamedQubit('q' + str(i)) for i in range(19)]

circuit = cirq.Circuit(
    cirq.X(q[1]),
    cirq.X(q[2]),
    cirq.X(q[3]),
    cirq.X(q[4]),
    cirq.X(q[5]),
    cirq.X(q[6]),
    cirq.X(q[7]),
    cirq.X(q[8]),
    cirq.X(q[16]),
    cirq.CNOT(q[0], q[8]),
    cirq.CNOT(q[0], q[16]),
    cirq.CCX(q[16], q[8], q[0]),
    cirq.CNOT(q[1], q[9]),
    cirq.CNOT(q[1], q[0]),
    cirq.CCX(q[0], q[9], q[1]),
    cirq.CNOT(q[2], q[10]),
    cirq.CNOT(q[2], q[1]),
    cirq.CCX(q[1], q[10], q[2]),
    cirq.CNOT(q[3], q[11]),
    cirq.CNOT(q[3], q[2]),
    cirq.CCX(q[2], q[11], q[3]),
    cirq.CNOT(q[3], q[17]),
    cirq.CCX(q[2], q[11], q[3]),
    cirq.CNOT(q[3], q[2]),
    cirq.CNOT(q[2], q[11]),
    cirq.CCX(q[1], q[10], q[2]),
    cirq.CNOT(q[2], q[1]),
    cirq.CNOT(q[1], q[10]),
    cirq.CCX(q[0], q[9], q[1]),
    cirq.CNOT(q[1], q[0]),
    cirq.CNOT(q[0], q[9]),
    cirq.CCX(q[16], q[8], q[0]),
    cirq.CNOT(q[0], q[16]),
    cirq.CNOT(q[16], q[8]),
    cirq.CNOT(q[4], q[12]),
    cirq.CNOT(q[4], q[17]),
    cirq.CCX(q[17], q[12], q[4]),
    cirq.CNOT(q[5], q[13]),
    cirq.CNOT(q[5], q[4]),
    cirq.CCX(q[4], q[13], q[5]),
    cirq.CNOT(q[6], q[14]),
    cirq.CNOT(q[6], q[5]),
    cirq.CCX(q[5], q[14], q[6]),
    cirq.CNOT(q[7], q[15]),
    cirq.CNOT(q[7], q[6]),
    cirq.CCX(q[6], q[15], q[7]),
    cirq.CNOT(q[7], q[18]),
    cirq.CCX(q[6], q[15], q[7]),
    cirq.CNOT(q[7], q[6]),
    cirq.CNOT(q[6], q[15]),
    cirq.CCX(q[5], q[14], q[6]),
    cirq.CNOT(q[6], q[5]),
    cirq.CNOT(q[5], q[14]),
    cirq.CCX(q[4], q[13], q[5]),
    cirq.CNOT(q[5], q[4]),
    cirq.CNOT(q[4], q[13]),
    cirq.CCX(q[17], q[12], q[4]),
    cirq.CNOT(q[4], q[17]),
    cirq.CNOT(q[17], q[12]),
    cirq.measure(q[0], key='meas0'),
    cirq.measure(q[1], key='meas1'),
    cirq.measure(q[2], key='meas2'),
    cirq.measure(q[3], key='meas3'),
    cirq.measure(q[4], key='meas4'),
    cirq.measure(q[5], key='meas5'),
    cirq.measure(q[6], key='meas6'),
    cirq.measure(q[7], key='meas7'),
    cirq.measure(q[8], key='meas8'),
    cirq.measure(q[9], key='meas9'),
    cirq.measure(q[10], key='meas10'),
    cirq.measure(q[11], key='meas11'),
    cirq.measure(q[12], key='meas12'),
    cirq.measure(q[13], key='meas13'),
    cirq.measure(q[14], key='meas14'),
    cirq.measure(q[15], key='meas15'),
    cirq.measure(q[16], key='meas16'),
    cirq.measure(q[17], key='meas17'),
    cirq.measure(q[18], key='meas18')
)

simulator = cirq.Simulator()
result = simulator.run(circuit, repetitions=1024)
result_dict = dict(result.multi_measurement_histogram(keys=['meas0', 'meas1', 'meas2', 'meas3', 'meas4', 'meas5', 'meas6', 'meas7', 'meas8', 'meas9', 'meas10', 'meas11', 'meas12', 'meas13', 'meas14', 'meas15', 'meas16', 'meas17', 'meas18']))
keys = list(map(lambda arr: reduce(lambda x, y: str(x) + str(y), arr[::-1]), result_dict.keys()))
counts = dict(zip(keys,[value for value in result_dict.values()]))
print(counts)